### ISSUE TITLE
Damned Sailor crashed the game

### ISSUE THREAD

**Issue by slard3** [peter1745/OceanicSurvival#1]
MC version: 1.15.2
Forge version: 31.1.26

I was on Survival Mode, spawned one mob and it crashed the game after a while.
[Crash report](https://hastebin.com/oquvejiwuk.pl)

**Comment by peter1745** [comment]
It's an issue with another mod that you use: Performant. It seems to be altering certain parts of the Task system for entities. I've removed two ai tasks that might cause issues. I haven't had any crashes with the Damned Sailor so I'm guessing the two mods are (for now) incompatible.
I'll release a new update today so feel free to download it and test it.
